# Generated by Django 5.2.8 on 2025-11-15 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('apontador', 'Apontador'), ('encarregado', 'Encarregado'), ('motorista', 'Motorista')], max_length=20, verbose_name='Tipo de Usuário')),
                ('funcao', models.CharField(blank=True, choices=[('engenheiro', 'Engenheiro'), ('tecnico', 'Técnico'), ('encarregado', 'Encarregado'), ('apontador', 'Apontador'), ('motorista', 'Motorista'), ('operador', 'Operador de Equipamento'), ('servente', 'Servente'), ('pedreiro', 'Pedreiro'), ('armador', 'Armador'), ('carpinteiro', 'Carpinteiro'), ('eletricista', 'Eletricista'), ('mecanico', 'Mecânico')], max_length=50, null=True, verbose_name='Função')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Obra')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('local', models.CharField(max_length=300, verbose_name='Local')),
                ('km_inicial', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='KM Inicial')),
                ('km_final', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='KM Final')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_prevista_fim', models.DateField(verbose_name='Data Prevista de Término')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída')], default='planejamento', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-created_at'],
            },
        ),
    ]
